---
    name: Checks

    on: [push]

    jobs:
        test-lint:
            name: Test and Lint
            runs-on: ubuntu-20.04
            steps:
                - name: Checkout
                  uses: actions/checkout@v2
                - name: Test Unittest
                  run: python -m unittest
                - name: Lint Pylint
                  run: pylint *
                - name: Lint Flake8
                  run: flake8 *