---
    name: Checks

    on: [push]

    jobs:
        test-lint:
            name: Test and Lint
            runs-on: ubuntu-20.04
            steps:
                - name: Checkout
                  uses: actions/checkout@v2
                - name: Install dependencies
                  run: make install
                - name: Test Unittest
                  run: |
                    make test
                - name: Lint Pylint
                  run: |
                    make pylint
                - name: make flake8
                  run: |
                    make flake8